In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [4]:
s = pd.date_range('2023-04-01','2023-04-10',freq = '10H').to_series()

In [5]:
s

2023-04-01 00:00:00   2023-04-01 00:00:00
2023-04-01 10:00:00   2023-04-01 10:00:00
2023-04-01 20:00:00   2023-04-01 20:00:00
2023-04-02 06:00:00   2023-04-02 06:00:00
2023-04-02 16:00:00   2023-04-02 16:00:00
2023-04-03 02:00:00   2023-04-03 02:00:00
2023-04-03 12:00:00   2023-04-03 12:00:00
2023-04-03 22:00:00   2023-04-03 22:00:00
2023-04-04 08:00:00   2023-04-04 08:00:00
2023-04-04 18:00:00   2023-04-04 18:00:00
2023-04-05 04:00:00   2023-04-05 04:00:00
2023-04-05 14:00:00   2023-04-05 14:00:00
2023-04-06 00:00:00   2023-04-06 00:00:00
2023-04-06 10:00:00   2023-04-06 10:00:00
2023-04-06 20:00:00   2023-04-06 20:00:00
2023-04-07 06:00:00   2023-04-07 06:00:00
2023-04-07 16:00:00   2023-04-07 16:00:00
2023-04-08 02:00:00   2023-04-08 02:00:00
2023-04-08 12:00:00   2023-04-08 12:00:00
2023-04-08 22:00:00   2023-04-08 22:00:00
2023-04-09 08:00:00   2023-04-09 08:00:00
2023-04-09 18:00:00   2023-04-09 18:00:00
Freq: 10H, dtype: datetime64[ns]

In [7]:
features = {
    'dayofweek': s.dt.dayofweek.values,
    'dayofyear':s.dt.dayofyear.values,
    'hour':s.dt.hour.values,
    'is_leap_year':s.dt.is_leap_year.values,
    'quarter':s.dt.quarter.values,
    'weekofyear':s.dt.weekofyear.values
    }

In [9]:
pd.DataFrame(features)

dayofweek  dayofyear  hour  is_leap_year  quarter  weekofyear
0           5         91     0         False        2          13
1           5         91    10         False        2          13
2           5         91    20         False        2          13
3           6         92     6         False        2          13
4           6         92    16         False        2          13
5           0         93     2         False        2          14
6           0         93    12         False        2          14
7           0         93    22         False        2          14
8           1         94     8         False        2          14
9           1         94    18         False        2          14
10          2         95     4         False        2          14
11          2         95    14         False        2          14
12          3         96     0         False        2          14
13          3         96    10         False        2          14
14          3         96    20         False        2          14
15          4         97     6         False        2          14
16          4         97    16         False        2          14
17          5         98     2         False        2          14
18          5         98    12         False        2          14
19          5         98    22         False        2          14
20          6         99     8         False        2          14
21          6         99    18         False        2          14

In [29]:
import random
import datetime


cat1 = [random.randint(1, 5) for _ in range(10)]
cat2 = [random.randint(1, 3) for _ in range(10)]
cat3 = [random.randint(0,2) for _ in range(10)]
num1 = [random.uniform(-2,2) for _ in range(10)]


start_date = datetime.date(2021, 1, 1)
end_date = datetime.date(2023, 12, 31)

month_range = range(1, 13)

year_range = range(start_date.year, end_date.year+1)

random_dates = [datetime.date(year=random.choice(year_range), month=random.choice(month_range), day=1) + datetime.timedelta(days=random.randint(0, 365)) for _ in range(10)]

num_digits = 5

customer_id = [random.randint(11, 20) for _ in range(10)]

df = pd.DataFrame({'date':random_dates,'customer_id':customer_id,'cat1':cat1,'cat2':cat2,'cat3':cat3,'num1':num1})


In [30]:
df['date'] = pd.to_datetime(df['date'])

In [31]:
df1 = df.copy()

In [32]:
df1['month'] = df['date'].dt.month
df1['year'] = df['date'].dt.year
df1['weekofyear'] = df['date'].dt.weekofyear
df1['dayofweek'] = df['date'].dt.dayofweek
df1['weekend'] = (df['date'].dt.weekday>=5).astype(int)

In [33]:
df1

date  customer_id  cat1  cat2  cat3      num1  month  year  \
0 2024-02-02           18     1     2     0 -1.317163      2  2024   
1 2024-07-18           11     1     2     0  0.354751      7  2024   
2 2024-02-06           19     1     2     0  0.456503      2  2024   
3 2024-04-30           20     1     3     0 -0.955660      4  2024   
4 2022-06-22           15     1     1     2  0.959049      6  2022   
5 2023-09-09           13     1     3     0  1.461329      9  2023   
6 2023-02-12           18     5     3     0 -1.559397      2  2023   
7 2023-01-31           15     4     3     0  1.324004      1  2023   
8 2023-12-06           20     3     1     0  1.534065     12  2023   
9 2023-07-12           11     4     3     0 -1.872164      7  2023   

   weekofyear  dayofweek  weekend  
0           5          4        0  
1          29          3        0  
2           6          1        0  
3          18          1        0  
4          25          2        0  
5          36          5        1  
6           6          6        1  
7           5          1        0  
8          49          2        0  
9          28          2        0

In [34]:
df1.groupby('customer_id').agg({'month':['nunique','mean']})

month     
            nunique mean
customer_id             
11                1  7.0
13                1  9.0
15                2  3.5
18                1  2.0
19                1  2.0
20                2  8.0

In [35]:
df1.groupby('customer_id').agg({'num1':['sum','min','max','mean']})

num1                              
                  sum       min       max      mean
customer_id                                        
11          -1.517413 -1.872164  0.354751 -0.758706
13           1.461329  1.461329  1.461329  1.461329
15           2.283054  0.959049  1.324004  1.141527
18          -2.876560 -1.559397 -1.317163 -1.438280
19           0.456503  0.456503  0.456503  0.456503
20           0.578405 -0.955660  1.534065  0.289203

In [40]:
def generate_features(df):
    df.loc[:,'month'] = df['date'].dt.month
    df.loc[:,'year'] = df['date'].dt.year
    df.loc[:,'weekofyear'] = df['date'].dt.weekofyear
    df.loc[:,'dayofweek'] = df['date'].dt.dayofweek
    df.loc[:,'weekend'] = (df['date'].dt.weekday>=5).astype(int)
    
    aggs ={}
    aggs['month'] = ['nunique','mean']        #df.agg({'col':['sum','mean']})
    aggs['weekofyear'] = ['nunique','mean']
    aggs['num1']= ['sum','mean','max','min']
    aggs['customer_id'] = ['size']            #get count of customer_id 
    
    agg_df = df.groupby('customer_id').agg(aggs)  #cust_idx becomes index col
    return agg_df.rest_index()               #to make customer_idx non index col

In [46]:
generate_features(df)

month      weekofyear            num1                      \
            nunique mean    nunique  mean       sum      mean       max   
customer_id                                                               
11                1  7.0          2  28.5 -1.517413 -0.758706  0.354751   
13                1  9.0          1  36.0  1.461329  1.461329  1.461329   
15                2  3.5          2  15.0  2.283054  1.141527  1.324004   
18                1  2.0          2   5.5 -2.876560 -1.438280 -1.317163   
19                1  2.0          1   6.0  0.456503  0.456503  0.456503   
20                2  8.0          2  33.5  0.578405  0.289203  1.534065   

                      customer_id  
                  min        size  
customer_id                        
11          -1.872164           2  
13           1.461329           1  
15           0.959049           2  
18          -1.559397           2  
19           0.456503           1  
20          -0.955660           2

MISSING VALUE IMPUATION USING KNN

In [62]:
from sklearn import impute
X = np.random.randint(1,15,(10,6))
X = X.astype(float)
X

array([[ 2.,  4.,  4., 14., 13., 13.],
       [ 2.,  3.,  5.,  1., 13.,  8.],
       [ 2., 13.,  1.,  9., 12.,  5.],
       [ 8.,  2.,  1.,  7., 14., 11.],
       [ 6.,  9., 11.,  3.,  4.,  8.],
       [10.,  7.,  9., 12.,  4.,  4.],
       [ 7.,  8., 11., 13.,  5.,  2.],
       [ 4.,  2.,  3., 11.,  6.,  8.],
       [13.,  1., 11., 12.,  8., 12.],
       [ 7.,  4.,  5., 14.,  4.,  9.]])

In [63]:
X.ravel()[np.random.choice(X.size,10,replace = False)] = np.nan

In [64]:
X

array([[ 2.,  4.,  4., 14., 13., 13.],
       [ 2.,  3.,  5., nan, 13.,  8.],
       [ 2., 13.,  1.,  9., 12., nan],
       [ 8.,  2.,  1.,  7., 14., 11.],
       [ 6.,  9., 11.,  3.,  4., nan],
       [10.,  7.,  9., nan,  4., nan],
       [nan, nan, 11., 13.,  5., nan],
       [ 4.,  2.,  3., 11.,  6.,  8.],
       [13., nan, 11., 12.,  8., 12.],
       [nan,  4.,  5., 14.,  4.,  9.]])

In [66]:
knn_imputer = impute.KNNImputer(n_neighbors=2)
knn_imputer.fit_transform(X)

array([[ 2. ,  4. ,  4. , 14. , 13. , 13. ],
       [ 2. ,  3. ,  5. , 12.5, 13. ,  8. ],
       [ 2. , 13. ,  1. ,  9. , 12. , 10.5],
       [ 8. ,  2. ,  1. ,  7. , 14. , 11. ],
       [ 6. ,  9. , 11. ,  3. ,  4. , 10. ],
       [10. ,  7. ,  9. ,  8. ,  4. , 10.5],
       [11.5,  5.5, 11. , 13. ,  5. , 10.5],
       [ 4. ,  2. ,  3. , 11. ,  6. ,  8. ],
       [13. ,  5.5, 11. , 12. ,  8. , 12. ],
       [ 7. ,  4. ,  5. , 14. ,  4. ,  9. ]])

Linear Regression imputation

In [134]:
#Using regression  to predict missing values
X = np.random.randint(1,15,(20,6))
X = X.astype(float)
X

array([[ 8.,  9., 13.,  9.,  9.,  7.],
       [ 8., 13., 14.,  8., 14.,  4.],
       [ 7., 10., 13.,  8.,  5.,  6.],
       [ 1., 14.,  3.,  9., 12., 12.],
       [ 1., 11.,  4., 14., 12., 10.],
       [ 5.,  5., 10., 13., 10., 13.],
       [ 6., 10.,  4.,  9.,  9., 11.],
       [ 1.,  1., 11., 12.,  8.,  4.],
       [ 3., 11.,  4.,  9.,  2.,  7.],
       [ 3., 13., 14.,  8.,  3.,  4.],
       [ 3.,  8., 11.,  6.,  5.,  5.],
       [ 2.,  5., 12., 11., 10., 10.],
       [ 9.,  6., 10.,  2., 10.,  8.],
       [13.,  7.,  8., 13., 10., 13.],
       [ 8., 11.,  4.,  1., 10., 12.],
       [ 7.,  1.,  8.,  3., 10.,  3.],
       [ 2.,  6., 12., 14., 12., 10.],
       [ 2.,  3., 11.,  9.,  5.,  4.],
       [14.,  1., 10.,  6.,  7.,  6.],
       [ 3.,  9., 11.,  1.,  3.,  4.]])

In [71]:
X.ravel()[np.random.choice(X.size,6,replace = False)] = np.nan
df = pd.DataFrame(X,columns = ['A','B','C','D','E','F'])

# Feature Selection

If the features have a very low variance (i.e. very close to 0), they
are close to being constant and thus, do not add any value to any model at all. It
would just be nice to get rid of them and hence lower the complexity

Univariate selection.
<li>scoreing each vol against target col.such as Mutual Info, ANOVA, F-test,chi2</li>
    <li>using SelectKBest
    <li>Chi2 used only when non-negative in nature.

In [138]:
class UnivariateFeatureSelection():
    def __init__(self,n_feature,problem_type,scoring):
        '''
        custom wrapper on different univariate features selction models of sklearn
        :param n_feature: SelectPercentile if float else SelecKBest
        :param problem_type : classification or regression
        :param scoring :scoring_function
        
        '''
        
        if problem_type == 'classification':
            valid_scoring = {
                'f_classif':f_classif,
                'chi2':chi2,
                'mutual_info_classif':mutual_info_classif
            }
        else:
            valid_scoring = {
                'f_regression':f_regression,
                'mutual_info_regression':mutual_info_regression
            }
        if scoring not in valid_scoring:
            raise Exception('Invalid Scoring Function')
        
        if isinstance(n_features,int):
            self.selection = SelectKBest(valid_scoring[scoring],k=n_features)
        elif isinstance(n_features,float):
            self.selection = SelectPercentile(valid_scoring[scoring],
                                             percentile=int(n_features*100))
        else:
            raise Exception('Invalid type of feature')
            
    def fit(self,X,y):
        return self.selection.fit(X,y)
 
        # same transform function
    def transform(self, X):
        return self.selection.transform(X)
    
    # same fit_transform function
    def fit_transform(self, X, y):
        return self.selection.fit_transform(X, y)

In [139]:
df = pd.DataFrame(X,columns = ['A','B','C','D','E','target'])
UnivariateFeatureSelection(n_feature = 4,problem_type = 'reg',scoring = 'f_regression')

NameError: name 'f_regression' is not defined